# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [1]:
import numpy as np
np.__version__
a=np.arange(30).reshape(2,3,5)
print(a)
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
print("list()只轉換第一階的資料, 但是 tolist()轉換全部的資料")

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
list(a):  [array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])]
tolist():  [[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]], [[15, 16, 17, 18, 19], [20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]]
list()只轉換第一階的資料, 但是 tolist()轉換全部的資料


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [13]:
# 記得先 Import 正確的套件
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2))

print(a)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(len(a))
print(type(a)) 

[0 8 1 8 1 4]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


In [14]:
print(b)
print(b.ndim)
print(b.shape)
print(b.size)
print(b.dtype)
print(b.itemsize)
print(len(b))
print(type(b)) 

[[8 2 1 8]
 [5 0 8 7]
 [2 9 9 6]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


In [15]:
print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(len(c))
print(type(c)) 

[[[4 2]
  [7 9]
  [0 4]]

 [[4 6]
  [8 1]
  [9 5]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [16]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[3, 4, 9, 4, 8, 6]
[3, 4, 9, 4, 8, 6]


In [17]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[7, 0, 5, 8], [9, 3, 9, 4], [1, 3, 7, 2]]
[array([7, 0, 5, 8]), array([9, 3, 9, 4]), array([1, 3, 7, 2])]


In [18]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[5, 6], [6, 2], [7, 4]], [[4, 2], [4, 6], [7, 6]]]
[array([[5, 6],
       [6, 2],
       [7, 4]]), array([[4, 2],
       [4, 6],
       [7, 6]])]


In [19]:
def newtolist(array):
    newlist = []
    if array.ndim == 3:
        for x in range(0,array.shape[0]):
            for y in range(0,array.shape[1]):
                newlist.append(list(c[x][y]))
        return newlist
    if array.ndim == 2:
        for x in range(0,array.shape[0]):
            newlist.append(list(array[x]))
        return newlist
    else:
        return list(array)

In [20]:
print(newtolist(a))
print(newtolist(b))
print(newtolist(c))

[3, 4, 9, 4, 8, 6]
[[7, 0, 5, 8], [9, 3, 9, 4], [1, 3, 7, 2]]
[[5, 6], [6, 2], [7, 4], [4, 2], [4, 6], [7, 6]]
