# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [6]:
import numpy as np
print(np.zeros((2,3)))
print(np.empty((2,3)))
#呼叫 zeros()、ones() 函式，可以依照傳入的形狀引數，建立元素全為 0、全為 1 的陣列。
#使用 empty() 函式則是不需要給定起始值，但是可以建立給定形狀的陣列，元素值則會隨機給定。

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [7]:
# 記得先 Import 正確的套件
import numpy as np

In [16]:
# 參考解答

a = np.random.rand(2, 3)
b = np.array(a, dtype="int")
print(a)
print(b)
'''
Your Code
'''

[[0.60283479 0.24942916 0.05495713]
 [0.33035342 0.71688766 0.25683243]]
[[0 0 0]
 [0 0 0]]


'\nYour Code\n'

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [23]:
m = 20
n = 40

c=np.random.randint(m,n,(2,3))
print(c)

[[25 38 32]
 [34 20 25]]
